services:
  backup:
    build: .
    environment:
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_BUCKET=${R2_BUCKET}
      - DB_PATH=${DB_PATH}
      - BACKUP_DIR=/backups
      - TZ=Asia/Istanbul
    volumes:
      - ${HOST_DB_PATH}:${DB_PATH}:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "backup-app", "|", "grep", "-v", "grep"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"